version: '3.8'

services:
  app:
    build: .
    container_name: soporte_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/supportdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  db:
    image: postgres:15
    container_name: soporte_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: soporte_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
